*&---------------------------------------------------------------------*
*& Report ZUSER_NEU_TEST
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*

INCLUDE zuser_neu_test_top                      .    " Global Data

CALL SCREEN '1000'.
INCLUDE zuser_neu_test_o01                      .  " PBO-Modules
INCLUDE zuser_neu_test_i01                      .  " PAI-Modules
INCLUDE zuser_neu_test_f01                      .  " FORM-Routines
